name: Build
on:
  push:
    branches:
      - master

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        BOARD: [rock-5b]
        DISTRO: [armbian]
        FLAVOR: [ubuntu]
        BRANCH: [legacy]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Armbian image
        uses: Mythologyli/armbian-compile-action@main
        if: matrix.DISTRO == 'armbian'
        with:
          branch: ${{ matrix.BRANCH }}
          board: ${{ matrix.BOARD }}
          flavor: ${{ matrix.FLAVOR }}
